### ISSUE TITLE
Support client_credentials grant_type

### ISSUE THREAD

**Issue by p53** [istio-ecosystem/authservice#95] opened 2020-05-11 14:00 UTC
I would like to use oidc for service to service authentication with client_credentials grant_type

**Comment by cfryanr** [comment] 2020-05-11 16:30
Hi, thanks so much for submitting your issue. This seems to be a duplicate of https://github.com/istio-ecosystem/authservice/issues/84 so closing this one in favor of #84. Please consider subscribing for notifications on #84.

**Closed by cfryanr** 2020-05-11 16:30 UTC
